package com.example.mytestapp.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class Admin implements Serializable {
    @TableId(type = IdType.ASSIGN_ID)
    @ApiModelProperty(notes = "AutoGenerated ID by MyBatisPlus")
    private Long id;
    @ApiModelProperty(notes = "The password-hashed of the admin")
    private String password;
    @ApiModelProperty(notes = "The username of the admin")
    private String username;
    @ApiModelProperty(notes = "The date of the admin generated")
    private Date date;
}
