package com.example.mytestapp.entity;


import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;

@Data
public class User implements Serializable{

    @TableId(type = IdType.ASSIGN_ID)
    @ApiModelProperty(notes = "AutoGenerated ID by MyBatisPlus")
    private Long id;
    @ApiModelProperty(notes = "The name of the user")
    private String name;
    @ApiModelProperty(notes = "The age of the user")
    private Integer age;
    @ApiModelProperty(notes = "The email of the user")
    private String email;
    @ApiModelProperty(notes = "The password-hashed of the user")
    private String password;
}
