spring:
  datasource:
    url: jdbc:mysql://localhost/yueheyi?characterEncoding=utf-8&useSSL=false
    username: root
    password: like101101
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.myself.mybatis.entity

